app/src/app/admin/profile/change-password/change-password.component.html
app/src/app/admin/profile/change-password/change-password.component.spec.ts
app/src/app/admin/profile/change-password/change-password.component.ts
app/src/app/admin/profile/profile-routing.module.ts
app/src/app/admin/profile/profile.module.ts
app/src/app/admin/profile/profile/profile.component.html
app/src/app/admin/profile/profile/profile.component.spec.ts
app/src/app/admin/profile/profile/profile.component.ts
app/src/app/app-routing.module.ts
app/src/app/layouts/admin-layout/admin-layout.component.html

profile & change-password routing

profile & change-password routing

---

app/src/app/admin/sales/sales.component.html
app/src/app/admin/sales/sales.component.scss
app/src/app/admin/sales/sales.component.ts
app/src/app/layouts/admin-layout/admin-layout.component.html
app/src/app/pages/forgot-password/forgot-password.component.html
app/src/app/pages/login/login.component.html
app/src/app/pages/login/login.component.ts
app/src/assets/css/sb-admin-2.css
app/src/styles.scss

sales order ui

---

app/src/app/admin/vendors/firm-statuses/firm-statuses.component.html
app/src/app/admin/vendors/firm-statuses/firm-statuses.component.ts
app/src/app/admin/vendors/gst-categories/gst-categories.component.html
app/src/app/admin/vendors/gst-categories/gst-categories.component.ts
app/src/app/admin/vendors/price-categories/price-categories.component.html
app/src/app/admin/vendors/price-categories/price-categories.component.ts
app/src/app/admin/vendors/vendor-agent/vendor-agent.component.html
app/src/app/admin/vendors/vendor-agent/vendor-agent.component.ts
app/src/app/admin/vendors/vendor-category/vendor-category.component.ts
app/src/app/admin/vendors/vendor-payment-terms/vendor-payment-terms.component.html
app/src/app/admin/vendors/vendor-payment-terms/vendor-payment-terms.component.ts
app/src/app/admin/vendors/vendors.component.ts
app/src/assets/css/sb-admin-2.css
app/src/styles.scss

vendor form ui and modal top alignment

---

app/src/app/admin/master/master-list/master-list.component.html
app/src/app/admin/user/roles/roles.component.ts
app/src/app/admin/user/user.component.ts
app/src/app/layouts/admin-layout/admin-layout.component.html
app/src/styles.scss

menu alignments and masters ui

---

app/src/app/admin/company/branches/branch-list/branch-list.component.ts
app/src/app/admin/leads/leads-list/leads-list.component.ts
app/src/app/admin/leads/leads.component.ts

Leads latest changes

---

app/src/app/admin/sales/sale-returns/sale-returns-list/sale-returns-list.component.ts
app/src/app/admin/sales/sale-returns/sale-returns.component.ts
app/src/app/admin/sales/salesinvoice/salesinvoice-list/salesinvoice-list.component.ts
app/src/app/admin/sales/salesinvoice/salesinvoice.component.ts

updated sales invoice and sale returns modules.

updated sale invoice and sale returns modules.

---

app/src/app/admin/vendors/vendors-list/vendors-list.component.ts
app/src/app/admin/vendors/vendors.component.ts

updated as per recent changes.

UI vendors final

---

app/projects/ta-table/src/lib/ta-table.component.html
app/projects/ta-table/src/lib/ta-table.component.ts
app/src/app/admin/inventory/inventory.component.ts
app/src/app/layouts/admin-layout/admin-layout.component.html

user roles icon changes
now both list data and filter data can be downloaded

Data download functionality

---

app/src/app/admin/assets/asset-maintenance/asset-maintenance.component.ts
app/src/app/admin/assets/assets.component.ts
app/src/app/admin/leads/leads.component.ts
app/src/app/admin/tasks/tasks.component.ts

changed submit button

---

app/src/app/admin/customers/customers.component.ts
app/src/app/admin/products/products.component.ts
app/src/app/admin/purchase/purchase-invoice/purchase-invoice.component.ts
app/src/app/admin/purchase/purchase.component.ts
app/src/app/admin/purchase/purchasereturnorders/purchasereturnorders.component.ts
app/src/app/admin/sales/sale-returns/sale-returns.component.ts
app/src/app/admin/sales/sales.component.ts
app/src/app/admin/sales/salesinvoice/salesinvoice.component.ts
app/src/app/admin/vendors/vendors.component.ts

updated sales, purchase, customers, Vendors, and Products modules

updated necessary changes.

---

app/src/app/admin/customers/customers.component.ts

updated customers field in form

updated customer fields.

---

app/src/app/admin/assets/asset-maintenance/asset-maintenance.component.ts
app/src/app/admin/assets/assets.component.ts
app/src/app/admin/company/company.component.ts
app/src/app/admin/customers/customer-payment-terms/customer-payment-terms.component.ts
app/src/app/admin/hrms/employee-list/employee-list.component.ts
app/src/app/admin/hrms/hrms.component.ts
app/src/app/admin/products/product-item-balance/product-item-balance.component.ts
app/src/app/admin/quickpacks/quickpacks-list/quickpacks-list.component.ts
app/src/app/admin/quickpacks/quickpacks.component.ts
app/src/app/admin/warehouses/warehouses-list/warehouses-list.component.ts
app/src/app/admin/warehouses/warehouses.component.ts

fixed ui changes in warehouse, quick packs, productitembalance, hrms

Data refresh assets leads hrms tasks masters

---

app/src/app/admin/inventory/inventory.component.ts
app/src/app/admin/products/products-list/products-list.component.ts
app/src/app/admin/products/products.component.ts

updated warehouse location and added checkbox for products.

Products and inventory curd operations

---

app/src/app/admin/sales/salesinvoice/salesinvoice.component.html
app/src/app/admin/sales/salesinvoice/salesinvoice.component.ts
app/src/app/admin/sales/salesinvoice/salesinvoice.module.ts

updated pending orders logic in sales invoice.

added pending orders to sale invoice module.

---

app/src/app/admin/sales/sale-receipt/sale-receipt-list/sale-receipt-list.component.html
app/src/app/admin/sales/sale-receipt/sale-receipt-list/sale-receipt-list.component.spec.ts
app/src/app/admin/sales/sale-receipt/sale-receipt-list/sale-receipt-list.component.ts
app/src/app/admin/sales/sale-receipt/sale-receipt-routing.module.ts
app/src/app/admin/sales/sale-receipt/sale-receipt.component.html
app/src/app/admin/sales/sale-receipt/sale-receipt.component.spec.ts
app/src/app/admin/sales/sale-receipt/sale-receipt.component.ts
app/src/app/admin/sales/sale-receipt/sale-receipt.module.ts
app/src/app/admin/sales/sales-dispatch/sales-dispatch.component.html
app/src/app/admin/sales/sales-dispatch/sales-dispatch.component.scss
app/src/app/admin/sales/sales-dispatch/sales-dispatch.component.spec.ts
app/src/app/admin/sales/sales-dispatch/sales-dispatch.component.ts
app/src/app/admin/sales/sales-list/sales-list.component.ts
app/src/app/admin/sales/sales-routing.module.ts
app/src/app/admin/sales/sales.component.ts
app/src/app/admin/sales/sales.module.ts
app/src/app/app-routing.module.ts
app/src/app/layouts/admin-layout/admin-layout.component.ts

added functionality for sale dispatch and sale receipt.

Sale dispatch & Sale receipt

---

app/src/app/admin/sales/sale-returns/sale-returns.component.ts

added logic for creating a sale order record from sale returns.

added sale order creation logic in sale returns.

---

app/projects/ta-table/src/lib/ta-table.component.ts
app/src/app/admin/assets/asset-maintenance/asset-maintenance-list/asset-maintenance-list.component.ts
app/src/app/admin/assets/assets-list/assets-list.component.ts
app/src/app/admin/company/branches/branch-list/branch-list.component.ts
app/src/app/admin/customers/customers-list/customers-list.component.ts
app/src/app/admin/finance/bank-account/bank-account-list/bank-account-list.component.ts
app/src/app/admin/finance/budget/budget-list/budget-list.component.ts
app/src/app/admin/finance/chart-of-accounts/chart-of-accounts-list/chart-of-accounts-list.component.ts
app/src/app/admin/finance/expense-claim/expense-claim-list/expense-claim-list.component.ts
app/src/app/admin/finance/financial-report/financial-report-list/financial-report-list.component.ts
app/src/app/admin/finance/journal-entry/journal-entry-list/journal-entry-list.component.ts
app/src/app/admin/finance/payment-transaction/payment-transaction-list/payment-transaction-list.component.ts
app/src/app/admin/finance/tax-configuration/tax-configuration-list/tax-configuration-list.component.ts
app/src/app/admin/hrms/employee-list/employee-list.component.ts
app/src/app/admin/leads/leads-list/leads-list.component.ts
app/src/app/admin/production/work-order-list/work-order-list.component.ts
app/src/app/admin/products/products-list/products-list.component.ts
app/src/app/admin/purchase/purchase-invoice/purchase-invoice-list/purchase-invoice-list.component.ts
app/src/app/admin/purchase/purchase-list/purchase-list.component.ts
app/src/app/admin/purchase/purchasereturnorders/purchasereturnorders-list/purchasereturnorders-list.component.ts
app/src/app/admin/quickpacks/quickpacks-list/quickpacks-list.component.ts
app/src/app/admin/sales/sale-receipt/sale-receipt-list/sale-receipt-list.component.ts
app/src/app/admin/sales/sale-returns/sale-returns-list/sale-returns-list.component.ts
app/src/app/admin/sales/sales-list/sales-list.component.ts
app/src/app/admin/sales/salesinvoice/salesinvoice-list/salesinvoice-list.component.ts
app/src/app/admin/tasks/tasks-list/tasks-list.component.ts
app/src/app/admin/vendors/vendors-list/vendors-list.component.ts
app/src/app/admin/warehouses/warehouses-list/warehouses-list.component.ts

Applying filters

---

app/src/app/admin/sales/credit-note/credit-note-list/credit-note-list.component.html
app/src/app/admin/sales/credit-note/credit-note-list/credit-note-list.component.spec.ts
app/src/app/admin/sales/credit-note/credit-note-list/credit-note-list.component.ts
app/src/app/admin/sales/credit-note/credit-note-routing.module.ts
app/src/app/admin/sales/credit-note/credit-note.component.html
app/src/app/admin/sales/credit-note/credit-note.component.scss
app/src/app/admin/sales/credit-note/credit-note.component.spec.ts
app/src/app/admin/sales/credit-note/credit-note.component.ts
app/src/app/admin/sales/credit-note/credit-note.module.ts
app/src/app/admin/sales/debit-note/debit-note-list/debit-note-list.component.html
app/src/app/admin/sales/debit-note/debit-note-list/debit-note-list.component.spec.ts
app/src/app/admin/sales/debit-note/debit-note-list/debit-note-list.component.ts
app/src/app/admin/sales/debit-note/debit-note-routing.module.ts
app/src/app/admin/sales/debit-note/debit-note.component.html
app/src/app/admin/sales/debit-note/debit-note.component.scss
app/src/app/admin/sales/debit-note/debit-note.component.spec.ts
app/src/app/admin/sales/debit-note/debit-note.component.ts
app/src/app/admin/sales/debit-note/debit-note.module.ts
app/src/app/admin/sales/sale-returns/sale-returns.component.ts
app/src/app/admin/sales/sales.component.ts
app/src/app/admin/sales/sales.module.ts
app/src/app/app-routing.module.ts
app/src/app/layouts/admin-layout/admin-layout.component.ts

added sale_credit_notes and sale_debit_notes modules.

added sale_credit & sale_debit notes moduels

---

app/src/app/admin/sales/sale-returns/sale-returns.component.ts

updated sale-return.component.ts file.

updated needed changes.

---

app/src/app/admin/sales/sales.component.ts

added flow_status field logic in sales module.

updated flow_status field in sales module.

---

app/src/app/admin/sales/sales.component.html
app/src/app/admin/sales/sales.component.scss
app/src/app/admin/sales/sales.component.ts

updated sale invocie creation button.

---

app/src/app/admin/sales/sales-list/sales-list.component.ts
app/src/app/admin/sales/sales.component.html
app/src/app/admin/sales/sales.component.scss
app/src/app/admin/sales/sales.component.ts

added sale estimate logic in sales.

Sale estimate UI

---

app/src/app/admin/purchase/purchase-invoice/purchase-invoice.component.html
app/src/app/admin/purchase/purchase.component.html
app/src/app/admin/purchase/purchasereturnorders/purchasereturnorders.component.html
app/src/app/admin/sales/sale-returns/sale-returns.component.html
app/src/app/admin/sales/sales.component.html
app/src/app/admin/sales/sales.component.scss
app/src/app/admin/sales/sales.component.ts
app/src/app/admin/sales/salesinvoice/salesinvoice.component.html

updated copy pop-up.

---

app/package-lock.json
app/package.json
app/src/app/admin/dashboard/dashboard.component.html
app/src/app/admin/dashboard/dashboard.component.scss
app/src/app/admin/dashboard/dashboard.component.ts
app/src/app/admin/master/master-list/master-list.component.ts
app/src/app/layouts/admin-layout/admin-layout.component.ts
app/src/assets/config.json

This branch is dedicated to the development of the dashboard functionality. Using this branch, I am implementing dynamic features that will make the dashboard interactive and responsive.

Dashboard reports

---

app/src/app/admin/reports/reports.component.html
app/src/app/admin/reports/reports.component.spec.ts
app/src/app/admin/reports/reports.component.ts
app/src/app/app-routing.module.ts
app/src/assets/config.json

This branch is for adding a reporting tool link so that the user can redirect to the reporting tool.

Added new component called reports to redirect user to reporting tool

---

app/src/app/admin/sales/sales.component.html
app/src/app/admin/sales/sales.component.ts

added credit limit functionality in FE

Added credit limit exceed logic

---

app/src/app/admin/quickpacks/quickpacks.component.ts
app/src/app/admin/sales/sales.component.ts

added necessary code and removed unnecessary codes.

updated code logics.

---

app/src/app/admin/sales/sale-returns/sale-returns.component.ts

updated sale order items logic.

updated sale_order_items

---

app/src/app/admin/purchase/purchase-invoice/purchase-invoice.component.ts
app/src/app/admin/purchase/purchase.component.ts
app/src/app/admin/purchase/purchasereturnorders/purchasereturnorders.component.ts
app/src/app/admin/sales/salesinvoice/salesinvoice.component.ts

updated color and size fields in purchase and sales module.

updated color and size fields in purchase and sales module.

---

app/src/app/admin/purchase/purchase-invoice/purchase-invoice.component.ts
app/src/app/admin/purchase/purchase.component.ts
app/src/app/admin/purchase/purchasereturnorders/purchasereturnorders-list/purchasereturnorders-list.component.ts
app/src/app/admin/purchase/purchasereturnorders/purchasereturnorders.component.ts
app/src/app/admin/sales/sale-returns/sale-returns.component.ts
app/src/app/admin/sales/sales.component.ts
app/src/app/admin/sales/salesinvoice/salesinvoice.component.ts

resolved issues in sales and purchase module.

resolved issues in sale_order_ui.

---

app/src/app/admin/products/products.component.ts
app/src/app/admin/purchase/purchase-invoice/purchase-invoice-list/purchase-invoice-list.component.html
app/src/app/admin/purchase/purchase-list/purchase-list.component.html
app/src/app/admin/purchase/purchasereturnorders/purchasereturnorders-list/purchasereturnorders-list.component.html
app/src/app/admin/sales/sale-returns/sale-returns-list/sale-returns-list.component.html
app/src/app/admin/sales/salesinvoice/salesinvoice-list/salesinvoice-list.component.html
app/src/app/admin/user/user.component.ts
app/src/app/admin/vendors/vendors.component.ts

Added Latest changes for User Component file

Added Latest changes for User Component file

---

app/projects/ta-form/src/ta-formly-ui-zero/fields/field-repeat/field-repeat.component.css
app/projects/ta-form/src/ta-formly-ui-zero/fields/field-repeat/field-repeat.component.html
app/projects/ta-form/src/ta-formly-ui-zero/fields/field-select/field-select.component.html
app/src/app/admin/sales/sales.component.html
app/src/app/admin/sales/sales.component.ts
app/src/app/admin/sales/salesinvoice/salesinvoice.component.html
app/src/app/admin/sales/salesinvoice/salesinvoice.component.ts
app/src/app/layouts/admin-layout/admin-layout.component.html
app/src/styles.scss

feb changes are applied in sales and sale invoice.

Issues pramod

---

app/src/app/admin/production/workorderboard/workorderboard.component.html
app/src/app/admin/purchase/purchase-invoice/purchase-invoice.component.ts
app/src/app/admin/purchase/purchase.component.ts
app/src/app/admin/purchase/purchasereturnorders/purchasereturnorders.component.ts
app/src/app/admin/sales/sale-returns/sale-returns.component.html
app/src/app/admin/sales/sale-returns/sale-returns.component.scss
app/src/app/admin/sales/sale-returns/sale-returns.component.ts
app/src/app/admin/sales/salesinvoice/salesinvoice.component.html
app/src/app/admin/sales/salesinvoice/salesinvoice.component.scss

Added UI changes sale and Purchase modules add product and Buttons modify like past order all.

Issues modify UI

---

app/src/app/admin/company/company.component.html
app/src/app/admin/company/company.component.ts
app/src/app/layouts/admin-layout/admin-layout.component.html
app/src/app/layouts/admin-layout/admin-layout.component.scss
app/src/app/layouts/admin-layout/admin-layout.component.ts
app/src/app/pages/forgot-password/forgot-password.component.html
app/src/app/pages/forgot-password/forgot-password.component.scss
app/src/assets/css/sb-admin-2.css
app/src/styles.scss

Responsive UI

---

app/src/app/admin/customers/customers-list/customers-list.component.ts
app/src/app/admin/finance/bank-account/bank-account-list/bank-account-list.component.ts
app/src/app/admin/finance/budget/budget-list/budget-list.component.ts
app/src/app/admin/finance/chart-of-accounts/chart-of-accounts-list/chart-of-accounts-list.component.ts
app/src/app/admin/finance/expense-claim/expense-claim-list/expense-claim-list.component.ts
app/src/app/admin/finance/financial-report/financial-report-list/financial-report-list.component.ts
app/src/app/admin/finance/journal-entry/journal-entry-list/journal-entry-list.component.ts
app/src/app/admin/finance/payment-transaction/payment-transaction-list/payment-transaction-list.component.ts
app/src/app/admin/finance/tax-configuration/tax-configuration-list/tax-configuration-list.component.ts
app/src/app/admin/inventory/inventory.component.ts
app/src/app/admin/production/bom/bom-list/bom-list.component.ts
app/src/app/admin/production/work-order-list/work-order-list.component.ts
app/src/app/admin/production/workorderboard/workorderboard.component.ts
app/src/app/admin/purchase/purchase-invoice/purchase-invoice-list/purchase-invoice-list.component.ts
app/src/app/admin/purchase/purchase-list/purchase-list.component.ts
app/src/app/admin/purchase/purchasereturnorders/purchasereturnorders-list/purchasereturnorders-list.component.ts
app/src/app/admin/sales/credit-note/credit-note-list/credit-note-list.component.ts
app/src/app/admin/sales/debit-note/debit-note-list/debit-note-list.component.ts
app/src/app/admin/sales/sale-receipt/sale-receipt-list/sale-receipt-list.component.ts
app/src/app/admin/sales/sale-receipt/sale-receipt.component.ts
app/src/app/admin/sales/sale-returns/sale-returns-list/sale-returns-list.component.ts
app/src/app/admin/sales/sales-dispatch/sales-dispatch.component.ts
app/src/app/admin/sales/sales-list/sales-list.component.ts
app/src/app/admin/sales/salesinvoice/salesinvoice-list/salesinvoice-list.component.ts
app/src/app/admin/stockjournal/stockjournal.component.ts
app/src/app/admin/vendors/vendors-list/vendors-list.component.ts

Sorting and order by lastest list

Sorting UI

---

app/src/app/admin/user/user.component.ts

Added code to not showing the logged-in user from the users list

Added code to not showing the logged-in user from the users list

---

app/src/app/admin/sales/sales.component.ts
app/src/app/admin/sales/salesinvoice/salesinvoice-list/salesinvoice-list.component.ts

resolved sale invoices issues.

resolved sale invoices issues.

---

app/src/app/admin/sales/sale-returns/sale-returns-list/sale-returns-list.component.ts

Workflow UI

---

app/src/app/admin/customers/customers.component.ts

UI custom fields

---

app/src/app/admin/customers/customers.component.scss
app/src/app/admin/vendors/vendors.component.html
app/src/app/admin/vendors/vendors.component.scss
app/src/app/admin/vendors/vendors.component.ts

custom fields logic for vendors in Frontend.

Vendor custom UI

---

app/src/app/admin/purchase/order-list/order-list.component.html
app/src/app/admin/purchase/order-list/order-list.component.spec.ts
app/src/app/admin/purchase/order-list/order-list.component.ts
app/src/app/admin/purchase/purchase.component.html
app/src/app/admin/purchase/purchase.component.ts

Added Past orders logic in Purchase module.

Purchase pastorders

---

app/src/app/layouts/admin-layout/admin-layout.component.html

company code will display dynamically for mobile view

Responsive for remaining modules

---

app/src/app/admin/assets/asset-categories/asset-categories.component.ts
app/src/app/admin/assets/asset-maintenance/asset-maintenance-list/asset-maintenance-list.component.ts
app/src/app/admin/assets/asset-maintenance/asset-maintenance.component.ts
app/src/app/admin/assets/asset-statuses/asset-statuses.component.ts
app/src/app/admin/assets/assets-list/assets-list.component.ts
app/src/app/admin/assets/assets.component.ts
app/src/app/admin/assets/locations/locations.component.ts
app/src/app/admin/dashboard/dashboard.component.ts
app/src/app/admin/sales/sale-returns/sale-returns.component.ts
app/src/app/admin/voiceassistant/voiceassistant.component.ts
app/src/app/layouts/admin-layout/admin-layout.component.ts
app/src/assets/config.json

changed base url.

---

app/projects/ta-form/src/lib/ta-form.component.ts
app/projects/ta-table/src/lib/ta-table.component.html
app/projects/ta-table/src/lib/ta-table.component.ts
app/src/app/admin/hrms/leave-approvals/leave-approvals.component.html
app/src/app/admin/purchase/purchase-invoice/purchase-invoice-list/purchase-invoice-list.component.html
app/src/app/admin/purchase/purchase-list/purchase-list.component.html
app/src/app/admin/purchase/purchasereturnorders/purchasereturnorders-list/purchasereturnorders-list.component.html
app/src/app/admin/sales/sale-returns/sale-returns-list/sale-returns-list.component.html
app/src/app/admin/sales/sales-list/sales-list.component.html
app/src/app/admin/sales/salesinvoice/salesinvoice-list/salesinvoice-list.component.html
app/src/app/pages/login/login.component.ts

Added refresh icon in all list pages and added pop-up message for incorrect login credentials

Added refresh & login msg show

---

app/src/app/admin/sales/sales.component.ts

updated invoice creation calculation.

updated invoice creation calculation.

---

app/src/app/admin/purchase/purchase-invoice/purchase-invoice.component.ts
app/src/app/admin/purchase/purchase.component.ts
app/src/app/admin/purchase/purchasereturnorders/purchasereturnorders.component.ts
app/src/app/admin/sales/sale-returns/sale-returns.component.ts
app/src/app/admin/sales/salesinvoice/salesinvoice.component.ts
app/src/app/admin/tasks/tasks.component.ts

added entityid's in all modules.

added entityid's in all modules.

---

app/src/app/admin/dashboard/dashboard.component.ts
app/src/app/admin/sales/sales.component.ts

Sales issues pramod

---

app/src/app/admin/sales/payment-receipt/payment-receipt-list.component.html
app/src/app/admin/sales/payment-receipt/payment-receipt-list.component.spec.ts
app/src/app/admin/sales/payment-receipt/payment-receipt-list.component.ts
app/src/app/admin/sales/payment-receipt/payment-receipt.component.html
app/src/app/admin/sales/payment-receipt/payment-receipt.component.ts

Added Payment receipt list in Payment Receipt form

Added Payment receipt list in Payment Receipt form

---

app/src/app/admin/customers/customers.component.ts
app/src/app/admin/purchase/purchase-invoice/purchase-invoice.component.ts
app/src/app/admin/purchase/purchase.component.ts
app/src/app/admin/purchase/purchasereturnorders/purchasereturnorders.component.ts
app/src/app/admin/sales/sale-returns/sale-returns.component.ts
app/src/app/admin/sales/sales.component.ts
app/src/app/admin/sales/salesinvoice/salesinvoice.component.ts
app/src/app/admin/tasks/tasks.component.ts
app/src/app/admin/utils/custom_field_fetch.ts
app/src/app/admin/vendors/vendors.component.ts

changed static field ids to dynamic values for getting custom fields.

changed static field ids to dynamic values for getting custom fields.

---

app/src/app/admin/sales/sales.component.ts
app/src/app/admin/sales/salesinvoice/salesinvoice.component.ts

added code logic for getting customer in sales and invoices.

added code logic for getting customer in sales and invoices.

---

app/projects/ta-table/src/lib/ta-table-config.ts
app/src/app/admin/purchase/purchase-invoice/purchase-invoice.component.ts
app/src/app/admin/purchase/purchase.component.ts
app/src/app/admin/purchase/purchasereturnorders/purchasereturnorders.component.ts
app/src/app/admin/sales/sale-receipt/sale-receipt.component.html
app/src/app/admin/sales/sale-receipt/sale-receipt.component.scss
app/src/app/admin/sales/sale-receipt/sale-receipt.component.ts
app/src/app/admin/sales/sale-returns/sale-returns.component.ts
app/src/app/admin/sales/sales-dispatch/sales-dispatch.component.ts
app/src/app/admin/sales/sales-list/sales-list.component.ts
app/src/app/admin/sales/sales.component.ts
app/src/app/admin/sales/salesinvoice/salesinvoice-list/salesinvoice-list.component.ts
app/src/app/admin/sales/salesinvoice/salesinvoice.component.ts

added logic for sales dispatch and sales receipts

Pramod testing

---

app/src/app/admin/finance/financial-report/financial-report.component.html
app/src/app/admin/finance/financial-report/financial-report.component.ts

Added code logic for financial reports.

Added code logic for financial reports.

---

app/src/app/admin/finance/financial-report/financial-report.component.html
app/src/app/admin/finance/financial-report/financial-report.component.ts

fetching the data values for calculation dynamically.

Financial reports

---

app/src/app/admin/customfields/customfields.component.ts
app/src/app/admin/dashboard/dashboard.component.html
app/src/app/admin/dashboard/dashboard.component.scss
app/src/app/admin/dashboard/dashboard.component.ts

added necessary changes

---

app/src/app/admin/customers/customer-categories/customer-categories.component.html
app/src/app/admin/customers/customer-categories/customer-categories.component.spec.ts
app/src/app/admin/customers/customer-categories/customer-categories.component.ts
app/src/app/admin/customers/customers-routing.module.ts
app/src/app/admin/customers/customers.module.ts
app/src/app/admin/master/master-list/master-list.component.html

added customer categories

---

app/src/app/admin/sales/sales.component.ts

Customer category

---

app/src/app/admin/sales/sales.component.ts

added sale type field functionality

added sale type field functinoality

---

app/src/app/admin/sales/sales.component.ts

added logic for invoice creation from sale_order

Sale child calc

---

app/src/app/admin/sales/sales.component.ts

updated parent and child sale orders.

updated parent and child sale orders.

---

app/src/app/admin/sales/salesinvoice/salesinvoice.component.ts

fixed sale invoice issue

---

app/src/app/admin/sales/orderslist/orderslist.component.ts
app/src/app/admin/sales/sale-returns/sale-returns.component.ts
app/src/app/admin/sales/saleinvoiceorderlist/saleinvoiceorderlist.component.ts
app/src/app/admin/sales/sales.component.ts
app/src/app/admin/sales/salesinvoice/salesinvoice.component.ts

added few necessary changes

---

app/src/app/admin/sales/sales-list/sales-list.component.html
app/src/app/admin/sales/sales-list/sales-list.component.scss
app/src/app/admin/sales/sales-list/sales-list.component.ts
app/src/app/admin/sales/sales.component.ts

added logic for email and preview pop-up logics

Email pop up

---

app/projects/ta-core/src/lib/net/default.interceptor.ts
app/src/app/admin/hrms/employee-list/employee-list.component.ts
app/src/app/admin/hrms/hrms.component.ts
app/src/app/admin/hrms/leave-approvals/leave-approvals.component.ts

Added full_name filed and other few changes

Added full)_name filed and other few changes

---

app/projects/ta-core/src/lib/net/default.interceptor.ts
app/projects/ta-form/src/ta-formly-ui-zero/fields/field-file/ta-file-upload/ta-file-upload.component.ts
app/src/app/admin/customers/customers.component.html
app/src/app/admin/customers/customers.component.ts
app/src/app/services/excel.service.ts

Create import button and UI model box and functionailty for customer

Create import button and UI model box and functionailty for customer

---

app/src/app/pages/activation/activation.component.html
app/src/app/pages/activation/activation.component.ts
app/src/app/pages/reset-password/reset-password.component.html
app/src/app/pages/reset-password/reset-password.component.scss
app/src/app/pages/reset-password/reset-password.component.ts

Added UI Pages for Reset-Password and user-activation with mail links

Added UI Pages for Reset-Password and user-activation with mail links

---

app/projects/ta-form/src/ta-formly-ui-zero/fields/field-repeat/field-repeat.component.ts
app/src/app/admin/customfields/customfields.component.ts
app/src/app/admin/inventory/inventory.component.ts
app/src/app/admin/production/workorder.component.html
app/src/app/admin/production/workorder.component.scss
app/src/app/admin/production/workorder.component.ts
app/src/app/admin/products/products.component.ts
app/src/app/admin/purchase/purchase-invoice/purchase-invoice-list/purchase-invoice-list.component.html
app/src/app/admin/quickpacks/quickpacks.component.ts
app/src/app/admin/reminders/reminders.component.ts
app/src/app/admin/sales/sales.component.ts
app/src/app/admin/workflow/workflow-list/workflow-list.component.ts
app/src/app/admin/workflow/workflow.component.html
app/src/app/admin/workflow/workflow.component.ts
app/src/app/app-routing.module.ts
app/src/app/layouts/admin-layout/admin-layout.component.html
app/src/app/layouts/admin-layout/admin-layout.component.scss
app/src/app/layouts/admin-layout/admin-layout.component.ts

added logics for the inventory, production and workflow.

Production inventory pramod fe

---

app/projects/ta-table/src/lib/ta-table.component.html
app/projects/ta-table/src/lib/ta-table.component.ts
app/src/app/admin/hrms/hrms.component.ts
app/src/app/admin/inventory/inventory.component.ts
app/src/app/admin/products/products-list/products-list.component.ts
app/src/app/admin/products/products.component.ts
app/src/app/admin/purchase/purchase-invoice/purchase-invoice.component.ts
app/src/app/admin/purchase/purchase.component.ts
app/src/app/admin/sales/sales.component.ts
app/src/app/admin/sales/salesinvoice/salesinvoice.component.ts

fixed the filters and also search

Master crud bharath- fixed the filters and also search

---

app/src/app/admin-commmon/fomrly-master-adv-select-fields.module.ts
app/src/app/admin/production/material-issue/material-issue.component.ts
app/src/app/admin/production/material-received/material-received.component.ts
app/src/app/admin/production/stock-summary/stock-summary.component.ts
app/src/app/utils/master-curd-config.ts
app/src/assets/config.json

master crudconfig productionFloors-dropdown

Materials issues to production floor-master crudconfig productionFloors-dropdown

---

app/src/app/admin/sales/sales.component.ts
app/src/app/admin/sales/salesinvoice/salesinvoice.component.ts
app/src/assets/config.json

Added url and custom field pop-up

Sale workflow new

---

app/src/app/admin/sales/salesinvoice/salesinvoice.component.ts

added logic for the product pull

added logic for the product pull
